### ISSUE TITLE
Support for keyCodes instead of keys

### ISSUE THREAD

**Issue by paulbjensen** [devlato/react-hotkeys#8]
Hi,

I'd like to add support for being able use keyCodes, so that we can capture key presses like the arrow keys.

**Comment by devlato** [comment]
@paulbjenses Would be great, I’ll check what I can do when I’ll have a spare time. Could you please provide an example of how do you want to use it?
P.S. I guess you can use arrow keys now. The codes are Up, Down, Left and Right :)

**Comment by paulbjensen** [comment]
Thanks,

We could probably pass ```keyCodes``` as a property to the component:

```
<HotKey keyCodes={[39]} onKeysCoincide={doSomething} />
```

Thanks for the tip, but it didn't work for me:

```
<HotKey keys={['Down']} onKeysCoincide={this.view('next')} />
```

**Comment by gwil** [comment]
@paulbjensen This component uses `e.key.toLowerCase()` so use:


`<HotKey keys={['arrowdown']} onKeysCoincide={this.view('next')} />`

Also `ArrowUp`, `ArrowLeft`, `ArrowRight`, other keys here:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

**Comment by devlato** [comment]
@gwil You're right, it's now `Down`, `Left` etc., it's `ArrowDown`, `ArrowLeft` etc. Thanks for responding!

**Comment by paulbjensen** [comment]
@gwil thank you, that has solved my use case, and I think we can close this Issue. Everyone happy to close it?
